CREATE DATABASE IF NOT EXISTS week_4;
USE week_4;

CREATE TABLE IF NOT EXISTS passwd (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    school VARCHAR(100) NOT NULL,
    profile_image VARCHAR(200) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS question (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modify_date TIMESTAMP NULL DEFAULT NULL,
    user_id INT NOT NULL,
    password VARCHAR(200) DEFAULT NULL,
    file_path VARCHAR(200) DEFAULT NULL,
    FOREIGN KEY(user_id) REFERENCES passwd(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS answer (
    id INT AUTO_INCREMENT PRIMARY KEY,
    question_id INT,
    content TEXT NOT NULL,
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modify_date TIMESTAMP NULL DEFAULT NULL,
    user_id INT,
    FOREIGN KEY(question_id) REFERENCES question(id) ON DELETE CASCADE,
    FOREIGN KEY(user_id) REFERENCES passwd(id) ON DELETE CASCADE
);